name: build and push docker

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  pull_request:
  push:
    branches:
      - master
  release:
    types: [published]
jobs:
  build_and_push:
    name: build and push docker
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: 1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          context: ./.github/workflows/docker
          file: ./.github/workflows/docker/Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/hydranet:latest
          no-cache: false
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/hydranet:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/hydranet:buildcache,mode=max
          push: ${{ github.event_name != 'pull_request'}}