name: Check Link

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  pull_request:

jobs:
  check_link:
    name: check link
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lycheeverse/lychee-action@v1.5.0
        id: lychee
        with:
          fail: true
          args: "--verbose --no-progress './**/*.md' './**/*.html' --timeout 1000 --max-concurrency 32 -T 1 --retry-wait-time 10"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}