name: CI
on: pull_request

jobs:
  ci:
    name: ci
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
        poetry-version: ["1.2.1"]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.poetry-version }}
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: install
        run: poetry install
      - name: test
        run: poetry run pytest
      - name: build
        run: poetry build
      - uses: actions/upload-artifact@v3
        with:
          name: onnx_files
          path: "*.onnx"
      - uses: actions/upload-artifact@v3
        with:
          name: torch_scripts
          path: "*.pt"
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: "dist/*"
  tensorrt:
    name: tensorrt
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: package
          path: .github/workflows/docker/tensorrt
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          tags: ghcr.io/${{ github.repository_owner }}/hydranet:latest
          no-cache: false
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/hydranet_tensorrt:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/hydranet_tensorrt:buildcache,mode=max
          push: ${{ github.event_name != 'pull_request'}}