name: Documentation

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  generate:
    name: Generate Documentation
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: "3.10.7"
    - name: Install mkdocs
      run: pip3 install mkdocs mkdocstrings mkdocs-material pymdown-extensions fontawesome_markdown markdown python-markdown-math plantuml-markdown mkdocs-codeinclude-plugin mkdocs-git-revision-date-localized-plugin plantuml
    - name: Build Document
      run: mkdocs build
    - uses: actions/upload-artifact@v2
      with:
        name: site
        path: site
        retention-days: 1
    - name: Publish Report
      if: ${{ github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'}}
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: site
        keep_files: false