name: Documentation

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  generate:
    name: Generate Documentation
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: "3.10.7"